// Gerado por stories/preparar.py. Não edite à mão: edite stories/roteiro.json.
window.DIAS = [
 {
  "id": "D01",
  "n": 1,
  "data": "qui 08/10",
  "fmt": "Reels",
  "hook": "Abra seu site no celular. Você tem 5 segundos.",
  "capa": "../posts/d01-teste-5-segundos/capa-v2.png",
  "pergunta": "Você já abriu seu site no celular hoje?",
  "resposta": "Responda: sim ou ainda não.",
  "palavra": "CHECKLIST",
  "bastidor": {
   "tipo": "quadros",
   "titulo": "Três quadros [do Reels de hoje.]",
   "imgs": [
    "assets/d01-q1.jpg",
    "assets/d01-q2.jpg",
    "assets/d01-q3.jpg"
   ],
   "texto": "600 quadros, 30 por segundo, cada movimento na batida da música."
  }
 },
 {
  "id": "D02",
  "n": 2,
  "data": "sex 09/10",
  "fmt": "Carrossel",
  "hook": "Uma landing page que converte tem 7 partes. Quantas a sua tem?",
  "capa": "../posts/d02-anatomia-landing-page/slide-01.png",
  "pergunta": "Sua landing page tem prova perto do botão?",
  "resposta": "Responda: tem ou não tem.",
  "palavra": null,
  "bastidor": {
   "tipo": "slides",
   "titulo": "O carrossel inteiro, [antes de ir ao ar.]",
   "imgs": [
    "../posts/d02-anatomia-landing-page/slide-01.png",
    "../posts/d02-anatomia-landing-page/slide-02.png",
    "../posts/d02-anatomia-landing-page/slide-03.png",
    "../posts/d02-anatomia-landing-page/slide-04.png",
    "../posts/d02-anatomia-landing-page/slide-05.png",
    "../posts/d02-anatomia-landing-page/slide-06.png",
    "../posts/d02-anatomia-landing-page/slide-07.png",
    "../posts/d02-anatomia-landing-page/slide-08.png",
    "../posts/d02-anatomia-landing-page/slide-09.png"
   ],
   "texto": "9 slides, revisados um a um no tamanho da tela do celular."
  }
 },
 {
  "id": "D03",
  "n": 3,
  "data": "sáb 10/10",
  "fmt": "Reels",
  "hook": "A Solvix não nasceu para fazer site bonito.",
  "capa": "../posts/d03-por-que-a-solvix-existe/capa.png",
  "pergunta": "Você já pagou por um site que ninguém entendia?",
  "resposta": "Responda: já ou nunca.",
  "palavra": "PREÇO",
  "bastidor": {
   "tipo": "trilha",
   "titulo": "A música de hoje [foi feita para este vídeo.]",
   "onda": [
    0.849,
    0.937,
    0.957,
    0.991,
    1.0,
    0.892,
    0.918,
    0.921,
    0.908,
    0.883,
    0.992,
    0.916,
    0.91,
    0.856,
    0.914,
    0.868,
    0.854,
    0.854,
    0.887,
    0.879,
    0.849,
    0.831,
    0.803,
    0.836,
    0.794,
    0.788,
    0.805,
    0.81,
    0.783,
    0.739,
    0.733,
    0.764,
    0.732,
    0.686,
    0.766,
    0.799,
    0.803,
    0.804,
    0.796,
    0.739,
    0.767,
    0.716,
    0.733,
    0.756,
    0.738,
    0.753,
    0.766,
    0.756,
    0.758,
    0.743,
    0.742,
    0.747,
    0.738,
    0.728,
    0.747,
    0.767,
    0.836,
    0.791,
    0.791,
    0.773,
    0.745,
    0.712,
    0.743,
    0.741,
    0.729,
    0.78,
    0.776,
    0.726,
    0.734,
    0.75,
    0.648,
    0.249
   ],
   "texto": "Sol maior, 104 BPM, Sol7M – Mim7 – Dó7M – Ré7. Cada efeito sonoro cai no tempo exato de um movimento."
  }
 },
 {
  "id": "D04",
  "n": 4,
  "data": "dom 11/10",
  "fmt": "Reels",
  "hook": "Mesma empresa. Mesmo serviço. Só mudamos a primeira tela.",
  "capa": "../posts/d04-redesign-clinica/capa.png",
  "pergunta": "Qual segmento você quer ver no próximo redesign?",
  "resposta": "Responda com o segmento.",
  "palavra": null,
  "bastidor": {
   "tipo": "quadros",
   "titulo": "Três quadros [do Reels de hoje.]",
   "imgs": [
    "assets/d04-q1.jpg",
    "assets/d04-q2.jpg",
    "assets/d04-q3.jpg"
   ],
   "texto": "697 quadros, 30 por segundo, cada movimento na batida da música."
  }
 },
 {
  "id": "D05",
  "n": 5,
  "data": "seg 12/10",
  "fmt": "Carrossel",
  "hook": "5 itens que toda landing page precisa antes de receber um real de anúncio.",
  "capa": "../posts/d05-checklist-landing-page/slide-01.png",
  "pergunta": "Você já ligou um anúncio sem revisar a página?",
  "resposta": "Responda: já ou nunca.",
  "palavra": "CHECKLIST",
  "bastidor": {
   "tipo": "slides",
   "titulo": "O carrossel inteiro, [antes de ir ao ar.]",
   "imgs": [
    "../posts/d05-checklist-landing-page/slide-01.png",
    "../posts/d05-checklist-landing-page/slide-02.png",
    "../posts/d05-checklist-landing-page/slide-03.png",
    "../posts/d05-checklist-landing-page/slide-04.png",
    "../posts/d05-checklist-landing-page/slide-05.png",
    "../posts/d05-checklist-landing-page/slide-06.png",
    "../posts/d05-checklist-landing-page/slide-07.png"
   ],
   "texto": "7 slides, revisados um a um no tamanho da tela do celular."
  }
 },
 {
  "id": "D06",
  "n": 6,
  "data": "ter 13/10",
  "fmt": "Reels",
  "hook": "Seu site é bonito. Mas ele vende?",
  "capa": "../posts/d06-site-decorativo/capa.png",
  "pergunta": "Seu site vende ou só enfeita?",
  "resposta": "Responda: vende ou enfeita.",
  "palavra": null,
  "bastidor": {
   "tipo": "codigo",
   "titulo": "O Reels de hoje começou [como código.]",
   "texto": "Cada cena, palavra e movimento é escrito num roteiro. O vídeo é gerado a partir dele, quadro a quadro.",
   "arquivo": "reels/roteiros/d06.js",
   "linhas": [
    "[",
    "  {",
    "    tipo: \"palavras\",",
    "    compassos: 2,",
    "    linhas: [",
    "      \"Seu site\",",
    "      \"é bonito.\",",
    "      \"[Mas ele vende?]\"",
    "    ],",
    "    tamanho: 150",
    "  },",
    "  {",
    "    tipo: \"celular\",",
    "    compassos: 4,",
    "    site: \"decorativo\",",
    "    label: \"Site decorativo · demonstração\",",
    "    carregar: 4,",
    "    destaques: [",
    "      {",
    "        beat: 5,",
    "        alvo: \".slider h4\",",
    "        texto: \"Não diz o que faz.\",",
    "        sub: \"“Inovação que transforma” serve …",
    "      },"
   ]
  }
 },
 {
  "id": "D07",
  "n": 7,
  "data": "qua 14/10",
  "fmt": "Carrossel",
  "hook": "Sites que posicionam. Sistemas que organizam. Visibilidade que traz clientes.",
  "capa": "../posts/d07-tres-frentes/slide-01.png",
  "pergunta": "Do que sua empresa precisa agora?",
  "resposta": "Responda: site, sistema ou Google.",
  "palavra": null,
  "bastidor": {
   "tipo": "slides",
   "titulo": "O carrossel inteiro, [antes de ir ao ar.]",
   "imgs": [
    "../posts/d07-tres-frentes/slide-01.png",
    "../posts/d07-tres-frentes/slide-02.png",
    "../posts/d07-tres-frentes/slide-03.png",
    "../posts/d07-tres-frentes/slide-04.png",
    "../posts/d07-tres-frentes/slide-05.png"
   ],
   "texto": "5 slides, revisados um a um no tamanho da tela do celular."
  }
 },
 {
  "id": "D08",
  "n": 8,
  "data": "qui 15/10",
  "fmt": "Reels",
  "hook": "Seu cliente não pesquisa seu nome. Ele pesquisa o que você faz.",
  "capa": "../posts/d08-busca-pelo-servico/capa.png",
  "pergunta": "Você aparece quando buscam o seu serviço?",
  "resposta": "Responda: apareço ou não sei.",
  "palavra": "ANÁLISE",
  "bastidor": {
   "tipo": "trilha",
   "titulo": "A música de hoje [foi feita para este vídeo.]",
   "onda": [
    0.92,
    0.962,
    0.836,
    1.0,
    0.846,
    0.881,
    0.896,
    0.702,
    0.879,
    0.936,
    0.651,
    0.861,
    0.865,
    0.808,
    0.779,
    0.738,
    0.765,
    0.706,
    0.68,
    0.698,
    0.695,
    0.645,
    0.694,
    0.699,
    0.649,
    0.704,
    0.708,
    0.714,
    0.646,
    0.633,
    0.644,
    0.635,
    0.57,
    0.642,
    0.686,
    0.605,
    0.672,
    0.622,
    0.652,
    0.584,
    0.61,
    0.631,
    0.606,
    0.584,
    0.644,
    0.656,
    0.556,
    0.641,
    0.619,
    0.612,
    0.585,
    0.594,
    0.611,
    0.586,
    0.579,
    0.617,
    0.647,
    0.572,
    0.609,
    0.621,
    0.557,
    0.646,
    0.62,
    0.648,
    0.626,
    0.622,
    0.647,
    0.639,
    0.573,
    0.641,
    0.535,
    0.174
   ],
   "texto": "Fá# maior, 104 BPM, Fá#7M – Mi♭m7 – Si7M – Dó#7. Cada efeito sonoro cai no tempo exato de um movimento."
  }
 },
 {
  "id": "D09",
  "n": 9,
  "data": "sex 16/10",
  "fmt": "Imagem",
  "hook": "Bonito não paga a conta. Claro paga.",
  "capa": "../posts/manifestos/manifesto-d09.png",
  "pergunta": "Na hora de escolher, pesa mais o bonito ou o claro?",
  "resposta": "Responda: bonito ou claro.",
  "palavra": null,
  "bastidor": {
   "tipo": "slides",
   "titulo": "A linha editorial [do mês.]",
   "imgs": [
    "../posts/manifestos/manifesto-d09.png",
    "../posts/manifestos/manifesto-d25.png",
    "../posts/manifestos/manifesto-d27.png"
   ],
   "texto": "Três frases, o mesmo grid e a mesma tipografia. Uma por semana no feed."
  }
 },
 {
  "id": "D10",
  "n": 10,
  "data": "sáb 17/10",
  "fmt": "Reels",
  "hook": "Um site pode custar R$1 mil ou R$35 mil. Aqui está a diferença.",
  "capa": "../posts/d10-quanto-custa-um-site/capa.png",
  "pergunta": "Você sabe o que define o preço de um site?",
  "resposta": "Responda: sei ou não sei.",
  "palavra": "PREÇO",
  "bastidor": {
   "tipo": "quadros",
   "titulo": "Três quadros [do Reels de hoje.]",
   "imgs": [
    "assets/d10-q1.jpg",
    "assets/d10-q2.jpg",
    "assets/d10-q3.jpg"
   ],
   "texto": "851 quadros, 30 por segundo, cada movimento na batida da música."
  }
 },
 {
  "id": "D11",
  "n": 11,
  "data": "dom 18/10",
  "fmt": "Reels",
  "hook": "O botão mais importante do seu site está escondido.",
  "capa": "../posts/d11-botao-whatsapp/capa.png",
  "pergunta": "Onde fica o WhatsApp no seu site?",
  "resposta": "Responda: no topo ou no rodapé.",
  "palavra": null,
  "bastidor": {
   "tipo": "codigo",
   "titulo": "O Reels de hoje começou [como código.]",
   "texto": "Cada cena, palavra e movimento é escrito num roteiro. O vídeo é gerado a partir dele, quadro a quadro.",
   "arquivo": "reels/roteiros/d11.js",
   "linhas": [
    "[",
    "  {",
    "    tipo: \"palavras\",",
    "    compassos: 2,",
    "    linhas: [",
    "      \"O botão mais\",",
    "      \"importante do\",",
    "      \"seu site está\",",
    "      \"[escondido.]\"",
    "    ],",
    "    tamanho: 128",
    "  },",
    "  {",
    "    tipo: \"celular\",",
    "    compassos: 3,",
    "    site: \"whats_escondido\",",
    "    label: \"Onde está o WhatsApp?\",",
    "    carregar: 1,",
    "    rolar: [",
    "      {",
    "        beat: 2,",
    "        y: 700,",
    "        dur: 1",
    "      },"
   ]
  }
 },
 {
  "id": "D12",
  "n": 12,
  "data": "seg 19/10",
  "fmt": "Carrossel",
  "hook": "Kaza Negócios. Curadoria de endereços, arquitetura e patrimônio.",
  "capa": "../posts/kaza-projeto/slide-01.png",
  "pergunta": "Menos cor pode deixar um site mais sofisticado?",
  "resposta": "Responda: pode ou não pode.",
  "palavra": "CHECKLIST",
  "bastidor": {
   "tipo": "slides",
   "titulo": "O carrossel inteiro, [antes de ir ao ar.]",
   "imgs": [
    "../posts/kaza-projeto/slide-01.png",
    "../posts/kaza-projeto/slide-02.png",
    "../posts/kaza-projeto/slide-03.png",
    "../posts/kaza-projeto/slide-04.png",
    "../posts/kaza-projeto/slide-05.png",
    "../posts/kaza-projeto/slide-06.png"
   ],
   "texto": "6 slides, revisados um a um no tamanho da tela do celular."
  }
 },
 {
  "id": "D13",
  "n": 13,
  "data": "ter 20/10",
  "fmt": "Reels",
  "hook": "Comecei o Instagram da Solvix com 0 seguidores. Vou mostrar tudo.",
  "capa": null,
  "pergunta": "Você acompanha os números do seu Instagram?",
  "resposta": "Responda: toda semana ou quase nunca.",
  "palavra": null,
  "bastidor": {
   "tipo": "painel",
   "titulo": "Onde cada post [é planejado.]",
   "img": "assets/painel.png",
   "texto": "Calendário, aprovação e resultado de cada post da Solvix num painel só."
  }
 },
 {
  "id": "D14",
  "n": 14,
  "data": "qua 21/10",
  "fmt": "Reels",
  "hook": "Redesenhei a página de uma academia em 3 decisões.",
  "capa": "../posts/d14-redesign-academia/capa.png",
  "pergunta": "No site de uma academia, o que você procura primeiro?",
  "resposta": "Responda: preço ou horário.",
  "palavra": null,
  "bastidor": {
   "tipo": "trilha",
   "titulo": "A música de hoje [foi feita para este vídeo.]",
   "onda": [
    0.914,
    0.993,
    0.712,
    0.991,
    1.0,
    0.711,
    0.924,
    0.962,
    0.639,
    0.914,
    0.915,
    0.661,
    0.785,
    0.854,
    0.716,
    0.74,
    0.778,
    0.635,
    0.684,
    0.716,
    0.591,
    0.633,
    0.662,
    0.55,
    0.651,
    0.644,
    0.579,
    0.68,
    0.684,
    0.592,
    0.613,
    0.664,
    0.566,
    0.57,
    0.615,
    0.518,
    0.643,
    0.654,
    0.552,
    0.604,
    0.64,
    0.565,
    0.593,
    0.614,
    0.528,
    0.606,
    0.597,
    0.443,
    0.595,
    0.61,
    0.553,
    0.59,
    0.607,
    0.534,
    0.557,
    0.603,
    0.471,
    0.551,
    0.581,
    0.446,
    0.65,
    0.683,
    0.621,
    0.614,
    0.643,
    0.589,
    0.622,
    0.629,
    0.583,
    0.594,
    0.376,
    0.121
   ],
   "texto": "Fá# mixolídio, 124 BPM, Fá#7 – Mi7M – Si7M – Fá#7. Cada efeito sonoro cai no tempo exato de um movimento."
  }
 },
 {
  "id": "D15",
  "n": 15,
  "data": "qui 22/10",
  "fmt": "Carrossel",
  "hook": "Landing page, site ou e-commerce? Escolher errado custa caro.",
  "capa": "../posts/d15-landing-site-ecommerce/slide-01.png",
  "pergunta": "Você sabe se precisa de landing, site ou loja?",
  "resposta": "Responda: sei ou não sei.",
  "palavra": "PREÇO",
  "bastidor": {
   "tipo": "slides",
   "titulo": "O carrossel inteiro, [antes de ir ao ar.]",
   "imgs": [
    "../posts/d15-landing-site-ecommerce/slide-01.png",
    "../posts/d15-landing-site-ecommerce/slide-02.png",
    "../posts/d15-landing-site-ecommerce/slide-03.png",
    "../posts/d15-landing-site-ecommerce/slide-04.png",
    "../posts/d15-landing-site-ecommerce/slide-05.png",
    "../posts/d15-landing-site-ecommerce/slide-06.png"
   ],
   "texto": "6 slides, revisados um a um no tamanho da tela do celular."
  }
 },
 {
  "id": "D16",
  "n": 16,
  "data": "sex 23/10",
  "fmt": "Reels",
  "hook": "Fiz o teste dos 5 segundos em 3 sites. Só um passou.",
  "capa": "../posts/d16-teste-tres-sites/capa.png",
  "pergunta": "O seu site passaria no teste dos 5 segundos?",
  "resposta": "Responda: passaria ou não sei.",
  "palavra": null,
  "bastidor": {
   "tipo": "quadros",
   "titulo": "Três quadros [do Reels de hoje.]",
   "imgs": [
    "assets/d16-q1.jpg",
    "assets/d16-q2.jpg",
    "assets/d16-q3.jpg"
   ],
   "texto": "836 quadros, 30 por segundo, cada movimento na batida da música."
  }
 },
 {
  "id": "D17",
  "n": 17,
  "data": "sáb 24/10",
  "fmt": "Carrossel",
  "hook": "4 coisas para exigir antes de pagar alguém para fazer seu site.",
  "capa": "../posts/d17-o-que-exigir/slide-01.png",
  "pergunta": "O domínio do seu site está no seu nome?",
  "resposta": "Responda: está ou não sei.",
  "palavra": "ANÁLISE",
  "bastidor": {
   "tipo": "slides",
   "titulo": "O carrossel inteiro, [antes de ir ao ar.]",
   "imgs": [
    "../posts/d17-o-que-exigir/slide-01.png",
    "../posts/d17-o-que-exigir/slide-02.png",
    "../posts/d17-o-que-exigir/slide-03.png",
    "../posts/d17-o-que-exigir/slide-04.png",
    "../posts/d17-o-que-exigir/slide-05.png",
    "../posts/d17-o-que-exigir/slide-06.png"
   ],
   "texto": "6 slides, revisados um a um no tamanho da tela do celular."
  }
 },
 {
  "id": "D18",
  "n": 18,
  "data": "dom 25/10",
  "fmt": "Carrossel",
  "hook": "5 coisas que a Solvix não faz. Nem por um preço maior.",
  "capa": "../posts/d18-o-que-a-solvix-nao-faz/slide-01.png",
  "pergunta": "Já ficou sem resposta depois da entrega de um site?",
  "resposta": "Responda: já ou nunca.",
  "palavra": null,
  "bastidor": {
   "tipo": "slides",
   "titulo": "O carrossel inteiro, [antes de ir ao ar.]",
   "imgs": [
    "../posts/d18-o-que-a-solvix-nao-faz/slide-01.png",
    "../posts/d18-o-que-a-solvix-nao-faz/slide-02.png",
    "../posts/d18-o-que-a-solvix-nao-faz/slide-03.png",
    "../posts/d18-o-que-a-solvix-nao-faz/slide-04.png",
    "../posts/d18-o-que-a-solvix-nao-faz/slide-05.png",
    "../posts/d18-o-que-a-solvix-nao-faz/slide-06.png",
    "../posts/d18-o-que-a-solvix-nao-faz/slide-07.png"
   ],
   "texto": "7 slides, revisados um a um no tamanho da tela do celular."
  }
 },
 {
  "id": "D19",
  "n": 19,
  "data": "seg 26/10",
  "fmt": "Reels",
  "hook": "Seu perfil no Google é a primeira página do seu site. E ninguém cuida dela.",
  "capa": "../posts/d19-perfil-google/capa.png",
  "pergunta": "Seu perfil no Google está atualizado?",
  "resposta": "Responda: está ou faz tempo.",
  "palavra": "CHECKLIST",
  "bastidor": {
   "tipo": "codigo",
   "titulo": "O Reels de hoje começou [como código.]",
   "texto": "Cada cena, palavra e movimento é escrito num roteiro. O vídeo é gerado a partir dele, quadro a quadro.",
   "arquivo": "reels/roteiros/d19.js",
   "linhas": [
    "[",
    "  {",
    "    tipo: \"palavras\",",
    "    compassos: 2,",
    "    linhas: [",
    "      \"Seu perfil no\",",
    "      \"Google é a\",",
    "      \"primeira página\",",
    "      \"[do seu site.]\"",
    "    ],",
    "    tamanho: 128",
    "  },",
    "  {",
    "    tipo: \"celular\",",
    "    compassos: 4,",
    "    site: \"perfil\",",
    "    label: \"Perfil de empresa · demonstração\",",
    "    carregar: 1,",
    "    destaques: [",
    "      {",
    "        beat: 2,",
    "        alvo: \".cat\",",
    "        texto: \"Categoria certa.\",",
    "        sub: \"É por ela que você aparece na bu…"
   ]
  }
 },
 {
  "id": "D20",
  "n": 20,
  "data": "ter 27/10",
  "fmt": "Carrossel",
  "hook": "Uma clínica que não existe. Um site que poderia existir amanhã.",
  "capa": "../posts/d20-projeto-conceitual-clinica/slide-01.png",
  "pergunta": "Você colocaria o nome da sua empresa num site assim?",
  "resposta": "Responda: colocaria ou mudaria algo.",
  "palavra": null,
  "bastidor": {
   "tipo": "slides",
   "titulo": "O carrossel inteiro, [antes de ir ao ar.]",
   "imgs": [
    "../posts/d20-projeto-conceitual-clinica/slide-01.png",
    "../posts/d20-projeto-conceitual-clinica/slide-02.png",
    "../posts/d20-projeto-conceitual-clinica/slide-03.png",
    "../posts/d20-projeto-conceitual-clinica/slide-04.png",
    "../posts/d20-projeto-conceitual-clinica/slide-05.png",
    "../posts/d20-projeto-conceitual-clinica/slide-06.png"
   ],
   "texto": "6 slides, revisados um a um no tamanho da tela do celular."
  }
 },
 {
  "id": "D21",
  "n": 21,
  "data": "qua 28/10",
  "fmt": "Reels",
  "hook": "\"Qualidade e excelência\" não diz nada. Seu cliente pulou essa frase.",
  "capa": "../posts/d21-texto-do-site/capa.png",
  "pergunta": "A primeira frase do seu site diz o que você faz?",
  "resposta": "Responda com a frase. Eu reescrevo.",
  "palavra": null,
  "bastidor": {
   "tipo": "trilha",
   "titulo": "A música de hoje [foi feita para este vídeo.]",
   "onda": [
    0.9,
    0.78,
    0.951,
    0.939,
    0.822,
    0.855,
    0.896,
    0.973,
    0.797,
    0.918,
    0.748,
    1.0,
    0.973,
    0.976,
    0.951,
    0.941,
    0.923,
    0.812,
    0.873,
    0.882,
    0.864,
    0.868,
    0.887,
    0.833,
    0.832,
    0.791,
    0.791,
    0.811,
    0.735,
    0.797,
    0.703,
    0.721,
    0.689,
    0.808,
    0.806,
    0.799,
    0.806,
    0.81,
    0.793,
    0.727,
    0.783,
    0.804,
    0.82,
    0.777,
    0.815,
    0.774,
    0.781,
    0.719,
    0.753,
    0.778,
    0.705,
    0.767,
    0.685,
    0.678,
    0.677,
    0.779,
    0.748,
    0.779,
    0.76,
    0.772,
    0.721,
    0.767,
    0.774,
    0.814,
    0.832,
    0.836,
    0.861,
    0.792,
    0.789,
    0.731,
    0.556,
    0.202
   ],
   "texto": "Dó# maior, 109 BPM, Si♭m7 – Fá#7M – Dó#7M – Lá♭7. Cada efeito sonoro cai no tempo exato de um movimento."
  }
 },
 {
  "id": "D22",
  "n": 22,
  "data": "qui 29/10",
  "fmt": "Carrossel",
  "hook": "Presença digital não é estar online.",
  "capa": "../posts/d22-tres-ideias/slide-01.png",
  "pergunta": "Quem visita seu site lembra de você depois?",
  "resposta": "Responda: lembra ou não sei.",
  "palavra": "PREÇO",
  "bastidor": {
   "tipo": "slides",
   "titulo": "O carrossel inteiro, [antes de ir ao ar.]",
   "imgs": [
    "../posts/d22-tres-ideias/slide-01.png",
    "../posts/d22-tres-ideias/slide-02.png",
    "../posts/d22-tres-ideias/slide-03.png",
    "../posts/d22-tres-ideias/slide-04.png",
    "../posts/d22-tres-ideias/slide-05.png"
   ],
   "texto": "5 slides, revisados um a um no tamanho da tela do celular."
  }
 },
 {
  "id": "D23",
  "n": 23,
  "data": "sex 30/10",
  "fmt": "Reels",
  "hook": "Numa loja online, a venda acontece ou morre na página do produto.",
  "capa": "../posts/d23-redesign-loja/capa.png",
  "pergunta": "Já desistiu de uma compra por causa do frete?",
  "resposta": "Responda: já ou nunca.",
  "palavra": null,
  "bastidor": {
   "tipo": "quadros",
   "titulo": "Três quadros [do Reels de hoje.]",
   "imgs": [
    "assets/d23-q1.jpg",
    "assets/d23-q2.jpg",
    "assets/d23-q3.jpg"
   ],
   "texto": "767 quadros, 30 por segundo, cada movimento na batida da música."
  }
 },
 {
  "id": "D24",
  "n": 24,
  "data": "sáb 31/10",
  "fmt": "Reels",
  "hook": "Seu site não passou no teste dos 5 segundos? Eu faço a análise por você.",
  "capa": "../posts/d24-analise-gratuita/capa.png",
  "pergunta": "Quer uma análise do seu site?",
  "resposta": "Responda: quero ou agora não.",
  "palavra": "ANÁLISE",
  "bastidor": {
   "tipo": "codigo",
   "titulo": "O Reels de hoje começou [como código.]",
   "texto": "Cada cena, palavra e movimento é escrito num roteiro. O vídeo é gerado a partir dele, quadro a quadro.",
   "arquivo": "reels/roteiros/d24.js",
   "linhas": [
    "[",
    "  {",
    "    tipo: \"palavras\",",
    "    compassos: 2,",
    "    linhas: [",
    "      \"Seu site\",",
    "      \"não passou no\",",
    "      \"teste dos\",",
    "      \"[5 segundos?]\"",
    "    ],",
    "    tamanho: 136,",
    "    label: \"Teste dos 5 segundos · ep. 3\"",
    "  },",
    "  {",
    "    tipo: \"palavras\",",
    "    compassos: 2,",
    "    linhas: [",
    "      \"Eu faço\",",
    "      \"[a análise]\",",
    "      \"[por você.]\"",
    "    ],",
    "    tamanho: 170,",
    "    top: 620",
    "  }"
   ]
  }
 },
 {
  "id": "D25",
  "n": 25,
  "data": "dom 01/11",
  "fmt": "Imagem",
  "hook": "Seu cliente decide em segundos. Seu site decide por você.",
  "capa": "../posts/manifestos/manifesto-d25.png",
  "pergunta": "Seu site diz quem você é antes do primeiro contato?",
  "resposta": "Responda: diz ou não sei.",
  "palavra": null,
  "bastidor": {
   "tipo": "slides",
   "titulo": "A linha editorial [do mês.]",
   "imgs": [
    "../posts/manifestos/manifesto-d09.png",
    "../posts/manifestos/manifesto-d25.png",
    "../posts/manifestos/manifesto-d27.png"
   ],
   "texto": "Três frases, o mesmo grid e a mesma tipografia. Uma por semana no feed."
  }
 },
 {
  "id": "D26",
  "n": 26,
  "data": "seg 02/11",
  "fmt": "Reels",
  "hook": "Seu site foi feito em 2019. Seu cliente percebe.",
  "capa": "../posts/d26-site-desatualizado/capa.png",
  "pergunta": "Seu site tem mais de três anos?",
  "resposta": "Responda: tem ou não tem.",
  "palavra": "CHECKLIST",
  "bastidor": {
   "tipo": "trilha",
   "titulo": "A música de hoje [foi feita para este vídeo.]",
   "onda": [
    0.815,
    0.938,
    0.931,
    0.952,
    0.934,
    1.0,
    0.96,
    0.893,
    0.925,
    0.898,
    0.823,
    0.895,
    0.858,
    0.883,
    0.851,
    0.817,
    0.863,
    0.841,
    0.799,
    0.865,
    0.756,
    0.731,
    0.786,
    0.746,
    0.78,
    0.736,
    0.748,
    0.801,
    0.74,
    0.649,
    0.688,
    0.669,
    0.673,
    0.692,
    0.738,
    0.721,
    0.756,
    0.755,
    0.759,
    0.727,
    0.719,
    0.77,
    0.689,
    0.656,
    0.711,
    0.702,
    0.726,
    0.703,
    0.677,
    0.706,
    0.718,
    0.699,
    0.707,
    0.695,
    0.674,
    0.687,
    0.653,
    0.636,
    0.683,
    0.709,
    0.669,
    0.726,
    0.754,
    0.768,
    0.725,
    0.685,
    0.738,
    0.74,
    0.755,
    0.753,
    0.562,
    0.204
   ],
   "texto": "Sol dórico, 108 BPM, Solm7 – Lám7 – Dó7 – Solm7. Cada efeito sonoro cai no tempo exato de um movimento."
  }
 },
 {
  "id": "D27",
  "n": 27,
  "data": "ter 03/11",
  "fmt": "Imagem",
  "hook": "Ninguém compra o que não entende.",
  "capa": "../posts/manifestos/manifesto-d27.png",
  "pergunta": "Um visitante entende seu negócio numa frase?",
  "resposta": "Responda: entende ou não sei.",
  "palavra": null,
  "bastidor": {
   "tipo": "slides",
   "titulo": "A linha editorial [do mês.]",
   "imgs": [
    "../posts/manifestos/manifesto-d09.png",
    "../posts/manifestos/manifesto-d25.png",
    "../posts/manifestos/manifesto-d27.png"
   ],
   "texto": "Três frases, o mesmo grid e a mesma tipografia. Uma por semana no feed."
  }
 },
 {
  "id": "D28",
  "n": 28,
  "data": "qua 04/11",
  "fmt": "Reels",
  "hook": "O site de R$300 costuma custar duas vezes.",
  "capa": "../posts/d28-barato-que-sai-caro/capa.png",
  "pergunta": "Você já pagou duas vezes pelo mesmo site?",
  "resposta": "Responda: já ou nunca.",
  "palavra": null,
  "bastidor": {
   "tipo": "quadros",
   "titulo": "Três quadros [do Reels de hoje.]",
   "imgs": [
    "assets/d28-q1.jpg",
    "assets/d28-q2.jpg",
    "assets/d28-q3.jpg"
   ],
   "texto": "807 quadros, 30 por segundo, cada movimento na batida da música."
  }
 },
 {
  "id": "D29",
  "n": 29,
  "data": "qui 05/11",
  "fmt": "Carrossel",
  "hook": "Tudo o que você precisa saber antes de falar com a Solvix. Inclusive o preço.",
  "capa": "../posts/d29-como-contratar/slide-01.png",
  "pergunta": "O que você quer saber antes de contratar um site?",
  "resposta": "Responda com a sua dúvida.",
  "palavra": "PREÇO",
  "bastidor": {
   "tipo": "slides",
   "titulo": "O carrossel inteiro, [antes de ir ao ar.]",
   "imgs": [
    "../posts/d29-como-contratar/slide-01.png",
    "../posts/d29-como-contratar/slide-02.png",
    "../posts/d29-como-contratar/slide-03.png",
    "../posts/d29-como-contratar/slide-04.png",
    "../posts/d29-como-contratar/slide-05.png",
    "../posts/d29-como-contratar/slide-06.png"
   ],
   "texto": "6 slides, revisados um a um no tamanho da tela do celular."
  }
 },
 {
  "id": "D30",
  "n": 30,
  "data": "sex 06/11",
  "fmt": "Reels",
  "hook": "30 dias atrás: 0 seguidores. Estes são os números de hoje.",
  "capa": null,
  "pergunta": "Qual post do mês mais te ajudou?",
  "resposta": "Responda com o número do post.",
  "palavra": null,
  "bastidor": {
   "tipo": "painel",
   "titulo": "Onde cada post [é planejado.]",
   "img": "assets/painel.png",
   "texto": "Calendário, aprovação e resultado de cada post da Solvix num painel só."
  }
 }
];
